import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const myFont = localFont({
  src: "./fonts/Graphik-Regular.woff2",
});

import "./Layout.css";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"app-container"}>
        <Header />

        <main className={"app-content"}>{children}</main>
      </body>
    </html>
  );
}
